settings:
  general:
    name: Spring-Boot-Application



spring:
  profiles:
    active: dev,postgre
#    active: dev,mysql
#Active Profile is always should two or more & The First one is must dev or prod and second or next is any database configuration


server:
  port: 2343