settings:
  general:
    name: Spring-Boot-Application



spring:
  profiles:
    active: dev,both,postgre
#    active: dev,stateless,postgre
#    active: dev,stateful,postgre
#    active: dev,mysql
#Active Profile is always should two or more & The First one is must dev or prod and next is application type like stateful or stateless third is any database configuration


server:
  port: 2343