#Enabled All Facilities for development & Debugging

spring-app:
    settings:
        security:
            secret-key: BHWTBWQE(&#RHDNKJLSH&EHWDJY*E(GKJOYFDW^FBSDSPYE()#RBHKJI
            session-live-time: 20F
            account:
                password:
                    recoverable: true
                    recovery-timeout-minutes: 5
                    recovery-code-length: 8
            authentication:
                maximum-live-session-count: 5
                maximum-login-limit-in-day: 200
                maximum-live-session-from-same-ip: 3
                jwt:
                    secret: WWpVek1XSXpOakE1TW1Kak5EbG1PRFpsTURGaU0yWmxZekV4TldKbFpHRmlNRE5qTVdabU1HVXdaakZpTnpZeU1qRXhaamN5WkRreE1HSmlNRGhpWm1FeVpUYzJNVEEwWVdNMFlqbG1aRFUxWXpsa00yUmxZV1pqWVdZd1lqZGlOREUzWW1ZNVpqQmpZelEyT1dGbU1EYzFZelJqWXpsaFpqVTVPR1UzTm1R
                    base64-secret: WWpVek1XSXpOakE1TW1Kak5EbG1PRFpsTURGaU0yWmxZekV4TldKbFpHRmlNRE5qTVdabU1HVXdaakZpTnpZeU1qRXhaamN5WkRreE1HSmlNRGhpWm1FeVpUYzJNVEEwWVdNMFlqbG1aRFUxWXpsa00yUmxZV1pqWVdZd1lqZGlOREUzWW1ZNVpqQmpZelEyT1dGbU1EYzFZelJqWXpsaFpqVTVPR1UzTm1R
                    token-validity-in-seconds: 300
                    token-validity-in-seconds-for-remember-me: 1800

            secure-channel:
                - dev

        mail:
            host: smtp.gmail.com
            port: 587
            username: springboottest420@gmail.com
            password: springboottest42kblkbl
            protocol: smtp
            debug: true
            smtp:
                auth: true
                starttls-enable: true
                ssl-trust: smtp.gmail.com


    database:
        hibernate:
            hbm2-ddl-auto: none
            format-sql: true
            comments: true
            show-sql: true
            enable-second-level-cache: true
            enable-strutured-cache: true
            enable-auto-evict-coll-cache: true
            enable-query-cache: true
        jpa:
            persistent-unit: SPRING

    cache:
        eh-cache:
            max-local-heap-size: 20M