settings:
  security:
    secretKey: BHWTBWQE(&#RHDNKJLSH&EHWDJY*E(GKJOYFDW^FBSDSPYE()#RBHKJI
    sessionLiveTime: 20F
    authentication:
      maximumLiveSessionCount: 5
      maximumLoginLimitInDay: 200
      maximumLiveSessionFromSameIp: 3
      jwt:
        secret: YjUzMWIzNjA5MmJjNDlmODZlMDFiM2ZlYzExNWJlZGFiMDNjMWZmMGUwZjFiNzYyMjExZjcyZDkxMGJiMDhiZmEyZTc2MTA0YWM0YjlmZDU1YzlkM2RlYWZjYWYwYjdiNDE3YmY5ZjBjYzQ2OWFmMDc1YzRjYzlhZjU5OGU3NmQ
        base64Secret: YjUzMWIzNjA5MmJjNDlmODZlMDFiM2ZlYzExNWJlZGFiMDNjMWZmMGUwZjFiNzYyMjExZjcyZDkxMGJiMDhiZmEyZTc2MTA0YWM0YjlmZDU1YzlkM2RlYWZjYWYwYjdiNDE3YmY5ZjBjYzQ2OWFmMDc1YzRjYzlhZjU5OGU3NmQ
        tokenValidityInSeconds: 300
        tokenValidityInSecondsForRememberMe: 1800


database:
  hibernate:
    hbm2DDLAuto: update
    formatSQL: true
    comments: true
    showSql: true
    enable-second-level-cache: true
    enableStruturedCache: true
    enableAutoEvictCollCache: true
    enableQueryCache: true
  jpa:
    persistentUnit: SPRING

cache:
  ehCache:
    maxLocalHeapSize: 20M