settings:
  general:
    name: Application
  security:
    secretKey: BHWTBWQE(&#RHDNKJLSH&EHWDJY*E(GKJOYFDW^FBSDSPYE()#RBHKJI
    sessionLiveTime: 20F



spring:
  profiles:
    active: dev,postgre



server:
  port: 2343