# If Added On Profile and Both wasn't present, then Application Work's Like Stateful

spring-app:
    settings:
        application-type:
        - STATEFUL
        session-creation-policy: IF_REQUIRED