# If Added On Profile Application Work's Like Stateless + Stateful

spring-app:
    settings:
        application-type:
            - STATELESS
            - STATEFUL
        session-creation-policy: IF_REQUIRED