settings:
  general:
    name: Application
  security:
    secretKey: BHWTBWQE(&#RHDNKJLSH&EHWDJY*E(GKJOYFDW^FBSDSPYE()#RBHKJI
    sessionLiveTime: 20F



spring:
  profiles:
    active: dev,postgre
#Active Profile is always should two or more & The First one is must dev or prod and second or next is any database configuration


server:
  port: 2343